# Generated by Django 2.0 on 2018-03-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeesapp', '0002_auto_20180301_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
